language: python
sudo: false
branches:
  only:
  - master
python:
- '3.6'
install:
- pip install --upgrade setuptools
- pip install -r requirements.txt
before_script:
  flake8 . 
  --ignore=F401 
  --ignore=F403
  --max-line-length=120
script:
- py.test adam --cov=adam --ignore=adam/tests/integration_tests/hypercube_test.py
after_success:
- coveralls
# disable encryption testing for Travis to pass
#before_install:
#- openssl aes-256-cbc -K $encrypted_3633a9d4c228_key -iv $encrypted_3633a9d4c228_iv
#  -in test_config.json.enc -out test_config.json -d
